- type: job
  id: ConscriptSniperDSM
  name: job-name-conscript-dsm-amr
  description: job-description-kadet #change me later
  playTimeTracker: ConscriptJobSniperDSM
  weight: 10
  startingGear: ConscriptSniperDSMGear
  alwaysUseSpawner: true
  icon: "JobIconKadet"
  requirements:
    - !type:FactionRequirement
      factionID: "DSM"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - Muted
        - WheelchairBound
  requireAdminNotify: false
  supervisors: job-supervisors-highcomm
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-soldat
  access:
  - Command
  - Maintenance
  - Service
  - DSMGeneral
  - DSMJail
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: ConscriptSniperDSMGear
  equipment:
    head: ClothingHeadHelmetImperialKnightCommanderHelmet
    mask: ClothingMaskImperialCombatGasmask
    jumpsuit: ClothingUniformJumpsuitImperialCombat
    outerClothing: ClothingOuterArmorImperialArmorPrestige
    shoes: ClothingShoesBootsImperialJackboots
    belt: ClothingBeltMilitaryWebbingFilledSniper
    gloves: ClothingHandsGlovesImperialLonggloves
    back: WeaponAntimaterielDSMJustice
    pocket1: WeaponPistolNeoVolker
    pocket2: GrenadeShrapnel
    ears: ClothingHeadsetEmpire
    id: LevymanPDA
    suitstorage: EmergencyOxygenTankFilled
