- type: job
  id: CoordinatorNCSP
  name: job-name-coordinator
  description: job-description-coordinator
  playTimeTracker: JobCoordinatorNCSP
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 8000
    - !type:FactionRequirement
      factionID: "TFSC"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
        - Blindness
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-syncoordinator
      - type: CPRTraining
      - type: SurgerySpeedModifier
        speedModifier: 2.5
  weight: 17
  startingGear: CoordinatorGear
  alwaysUseSpawner: true
  icon: "JobIconSyndieCoordinator"
  requireAdminNotify: true
  supervisors: You answer to the interests of the Interdyne Pharmaceuticals company. Organize your employees. Keep track of stock. See to it that contracts are fullfilled.
  canBeAntag: false
  access:
  - Command
  - Maintenance
  - SyndicateBasic
  - SyndicateInterdyne
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: CoordinatorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndicateInterdyneWhiteUniform
    gloves: ClothingHandsGlovesCombat
    mask: ClothingMaskSyndicateFacemask
    shoes: ClothingShoesBootsCombat
    outerClothing: ClothingOuterArmorSyndicateCoordinator
    head: ClothingHeadHatSyndicateInterdyneBeret
    id: CoordinatorPDA
    back: ClothingBackpackNCSPFilledInfanteer
    ears: ClothingHeadsetNCSPInterdyne
