- type: latheRecipe
  id: ServiceRollingPin
  result: RollingPin
  completetime: 1
  materials:
    Wood: 200

- type: latheRecipe
  id: ServiceSpoon
  result: Spoon
  completetime: 1
  materials:
    Steel: 75

- type: latheRecipe
  id: ServiceFork
  result: Fork
  completetime: 1
  materials:
    Steel: 75

- type: latheRecipe
  id: ServicePairedChopsticks
  result: PairedChopsticks
  completetime: 1
  materials:
    Glass: 100
