- type: job
  id:
  name: job-name-mechanic
  description: job-description-mechanic
  playTimeTracker:
  weight: 1
  startingGear:
  alwaysUseSpawner: true
  icon:
  requirements:
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - WheelchairBound
  requireAdminNotify: false
  supervisors: job-supervisors-highcomm
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank:
  access:
  - Command
  - Maintenance
  - Service
  - NCWLGeneral
  - NCWLJail
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id:
  equipment:
    shoes:
    jumpsuit:
    ears:
    pocket1:
    id:
