- type: job
  id:
  name: job-name-ncwl-medical-director
  description: job-description-ncwl-medical-director
  playTimeTracker:
  weight: 1
  startingGear:
  alwaysUseSpawner: true
  icon:
  requirements:
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - WheelchairBound
  requireAdminNotify: false
  supervisors: job-supervisors-highcomm
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ncwl-medi-leader
  access:
  - Command
  - Maintenance
  - Service
  - NCWLGeneral
  - NCWLJail
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: DirectorNCWLGear
  equipment:
    shoes: ClothingShoesBootsJack
    jumpsuit: ClothingUniformJumpsuitNCWLMedic
    id: NCWLMedicalLeaderPDA
    outerClothing: ClothingOuterArmorNCWLCarapaceVrachev
    belt: ClothingBeltMedicalFilled
    back: ClothingBackpackNCWL
    gloves: ClothingHandsGlovesNitrile
    head: ClothingHeadHatNCWLBeretMedi
    eyes: ClothingEyesHudMedSec
    ears: ClothingHeadsetNCWL
