- type: job
  id: DockmasterNCWL
  name: job-name-ncwl-logistic-dockmaster
  description: job-description-ncwl-logistic-dockmaster
  playTimeTracker: JobLogisticLeaderNCWL
  weight: 3
  startingGear: DockmasterNCWLGear
  alwaysUseSpawner: true
  icon: "JobIconNCWLLogisticLeader"
  requirements:
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - WheelchairBound
  requireAdminNotify: false
  supervisors: job-supervisors-highcomm
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ncwl-logi-leader
  access:
  - Command
  - Maintenance
  - Service
  - NCWLGeneral
  - NCWLJail
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: DockmasterNCWLGear
  equipment:
    shoes: ClothingShoesBootsSalvage
    jumpsuit: ClothingUniformJumpsuitNCWLTelnikSleeved
    id: NCWLLogisticLeaderPDA
    outerClothing: ClothingOuterArmorNCWLLogi
    belt: ClothingBeltSalvageWebbing
    back: ClothingBackpackNCWL
    gloves: ClothingHandsGlovesFingerless
    head: ClothingHeadHatBeretQM
    ears: ClothingHeadsetNCWL
