- type: job
  id: CaptainNCWL
  name: job-name-ncwl-homeguard-captain
  description: job-description-ncwl-homeguard-captain
  playTimeTracker: JobHomeguardSquadCaptainNCWL
  weight: 9
  startingGear: CaptainNCWLGear
  alwaysUseSpawner: true
  icon: "JobIconNCWLHomeguardSquadCaptain"
  requirements:
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - WheelchairBound
  requireAdminNotify: false
  supervisors: job-supervisors-highcomm
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ncwl-home-squad-lead
  access:
  - Command
  - Maintenance
  - Service
  - NCWLGeneral
  - NCWLJail
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: CaptainNCWLGear
  equipment:
    shoes: ClothingShoesBootsJack
    jumpsuit: ClothingUniformJumpsuitNCWL
    id: NCWLHomeguardSquadCaptainPDA
    outerClothing: ClothingOuterArmorNCWLCarapaceKapitan
    belt: ClothingBeltNCWLPouches
    pocket1: WeaponPistolHKUSP
    back: ClothingBackpackNCWL
    gloves: ClothingHandsGlovesCombat
    head: ClothingHeadHatNCWLBeret
    ears: ClothingHeadsetNCWL
