- type: job
  id: CommandantNCWL
  name: job-name-ncwl-faction-leader
  description: job-description-ncwl-faction-leader
  playTimeTracker: JobFactionLeaderNCWL
  weight: 12
  startingGear: CommandantNCWLGear
  alwaysUseSpawner: true
  icon: "JobIconNCWLFactionLeader"
  requirements:
    - !type:CharacterWhitelistRequirement
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - WheelchairBound
  requireAdminNotify: false
  supervisors: job-supervisors-highcomm
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ncwl-faction-leader
  access:
  - Command
  - Maintenance
  - Service
  - NCWLGeneral
  - NCWLJail
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: CommandantNCWLGear
  equipment:
    shoes: ClothingShoesBootsNCWLAdmiralParade
    jumpsuit: ClothingUniformJumpsuitNCWLCommunications
    id: NCWLFactionLeaderPDA
    outerClothing: ClothingOuterArmorNCWLOpremeCarapace
    belt: ClothingBeltNCWLDoubleHolster
    pocket1: WeaponRevolverPython
    pocket2: WeaponRevolverPython
    back: ClothingBackpackNCWL
    gloves: ClothingHandsGlovesNCWLAdmiralParade
    head: ClothingHeadHatNCWLBeretAdmiral
    ears: ClothingHeadsetNCWL
