- type: job
  id:
  name: job-name-ncwl-homeguard-coordinator
  description: job-description-ncwl-homeguard-coordinator
  playTimeTracker:
  weight: 1
  startingGear:
  alwaysUseSpawner: true
  icon:
  requirements:
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - WheelchairBound
  requireAdminNotify: false
  supervisors: job-supervisors-highcomm
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ncwl-home-leader
  access:
  - Command
  - Maintenance
  - Service
  - NCWLGeneral
  - NCWLJail
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: CoordinatorNCWLGear
  equipment:
    shoes: ClothingShoesBootsJack
    jumpsuit: ClothingUniformJumpsuitNCWLKommissar
    id: NCWLHomeguardLeaderPDA
    outerClothing: ClothingOuterArmorNCWLCarapace
    belt: ClothingBeltNCWLPouches
    back: ClothingBackpackNCWL
    gloves: ClothingHandsGlovesCombat
    head: ClothingHeadHatNCWLKommissarHat
    ears: ClothingHeadsetNCWL
