- type: job
  id: WorkerNCWL
  name: job-name-worker
  description: job-description-worker
  playTimeTracker: JobKadetNCWL
  weight: 1
  startingGear: WorkerGear
  alwaysUseSpawner: true
  icon: "JobIconKadet"
  requirements:
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - WheelchairBound
  requireAdminNotify: false
  supervisors: job-supervisors-highcomm
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-soldat
  access:
  - Command
  - Maintenance
  - Service
  - NCWLGeneral
  - NCWLJail
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: WorkerGear
  equipment:
    shoes: ClothingShoesBootsJack
    jumpsuit: ClothingUniformJumpsuitNCWL
    ears: ClothingHeadsetNCWL
    pocket1: WeaponPistolHKUSP
    id: KadetPDA
