- type: job
  id: ArtificerNCWL
  name: job-name-artificer
  description: job-description-artificer
  playTimeTracker: JobArtificerNCWL
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 20000
    - !type:CharacterFactionRequirement
      factionID: "NCWL"
  weight: 20
  startingGear: ArtificerGear
  alwaysUseSpawner: true
  icon: "JobIconArtificer"
  requireAdminNotify: false
  supervisors: job-supervisors-highcomm
  canBeAntag: false
  access:
  - Command
  - Maintenance
  - NCWLGeneral
  - NCWLJail
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: ArtificerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitNCWLArtificer
    id: ArtificerPDA
    ears: ClothingHeadsetNCWL
    belt: ClothingBeltUtilityEngineering
    pocket1: WeaponPistolHKUSP
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHatNCWLBeret
