- type: job
  id: DoktorNCWL
  name: job-name-doktor
  description: job-description-doktor
  playTimeTracker: JobDoktorNCWL
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 20000
    - !type:FactionRequirement
      factionID: "NCWL"
  weight: 22
  startingGear: DoktorGear
  alwaysUseSpawner: true
  icon: "JobIconDoktor"
  requireAdminNotify: false
  supervisors: job-supervisors-highcomm
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-doktor
  access:
  - Command
  - Maintenance
  - NCWLGeneral
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: DoktorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitNCWLMedic
    shoes: ClothingShoesColorBlack
    id: DoktorPDA
    ears: ClothingHeadsetNCWL
    belt: ClothingBeltMedicalFilled
    pocket1: WeaponPistolHKUSP
    outerClothing: ClothingOuterArmorNCWLCarapaceDoktor
    head: ClothingHeadHatNCWLCapsoftMedical
