- type: job
  id: ConscriptKadetNCWL
  name: job-name-conscript-ncwl-cadet
  description: job-description-kadet
  playTimeTracker: ConscriptJobKadetNCWL
  weight: 10
  startingGear: ConscriptKadetGear
  alwaysUseSpawner: true
  icon: "JobIconKadet"
  requirements:
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - Muted
        - WheelchairBound
  requireAdminNotify: false
  supervisors: job-supervisors-highcomm
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-soldat
  access:
  - Command
  - Maintenance
  - Service
  - NCWLGeneral
  - NCWLJail
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: ConscriptKadetGear
  equipment:
    shoes: ClothingShoesBootsJack
    jumpsuit: ClothingUniformJumpsuitNCWL
    ears: ClothingHeadsetNCWL
    belt: WeaponPistolHKUSP
    id: KadetPDA
    head: ClothingHeadHatNCWLCapsoft
