- type: entity
  id: StandardCrescentStation #Main faction stations
  parent:
    - BaseStation
    - BaseStationCargo
    - BaseStationJobsSpawning
    - BaseStationRecords
    - BaseStationShuttles
    - BaseStationAlertLevels
    - BaseStationSiliconLawCrescentStation
    - BaseStationSectorNews
  categories: [ HideSpawnMenu ]
  components:
    - type: Transform
#    - type: ShipRenameHolopad # i assume not here because there could be multiple holopads

- type: entity
  id: StandardCrescentOutpost #POI
  parent:
    - BaseStation
    - BaseStationCargo
    - BaseStationJobsSpawning
    - BaseStationRecords
    - BaseStationShuttles
    - BaseStationAlertLevels
    - BaseStationSiliconLawCrescentStation
  categories: [ HideSpawnMenu ]
  components:
    - type: Transform
    - type: ShipRenameHolopad

- type: entity
  id: StandardCrescentVessel #Combat vessel
  parent:
    - BaseStation
    - BaseStationJobsSpawning
    - BaseStationRecords
    - BaseStationCargo
    - BaseCombatShipAlertLevels
    - BaseStationAllEventsEligible
    - BaseStationRenameFaxes
    - BaseStationSiliconLawCrescentShips
  categories: [ HideSpawnMenu ]
  components:
    - type: Transform
    - type: ShipRenameHolopad

- type: entity
  id: StandardCrescentCivilianVessel #Civilian / unarmed vessel
  parent:
    - BaseStation
    - BaseStationJobsSpawning
    - BaseStationRecords
    - BaseStationAlertLevels
    - BaseStationAllEventsEligible
    - BaseStationRenameFaxes
    - BaseStationCargo
    - BaseStationSiliconLawCrescentShips
  categories: [ HideSpawnMenu ]
  components:
    - type: Transform
    - type: ShipRenameHolopad

- type: entity
  id: StandardCrescentExpeditionVessel #Expeds
  parent:
    - BaseStation
    - BaseStationJobsSpawning
    - BaseStationRecords
    - BaseStationAlertLevels
    - BaseStationAllEventsEligible
    - BaseStationRenameFaxes
    - BaseStationCargo
    - BaseStationSiliconLawCrescentShips
    - BaseStationExpeditions
  categories: [ HideSpawnMenu ]
  components:
    - type: Transform
    - type: ShipRenameHolopad

- type: entity
  id: StandardCrescentExpeditionVesselCombat #Expeds
  parent:
    - BaseStation
    - BaseStationJobsSpawning
    - BaseStationRecords
    - BaseCombatShipAlertLevels
    - BaseStationAllEventsEligible
    - BaseStationRenameFaxes
    - BaseStationCargo
    - BaseStationSiliconLawCrescentShips
    - BaseStationExpeditions
  categories: [ HideSpawnMenu ]
  components:
    - type: Transform
    - type: ShipRenameHolopad

- type: entity
  id: BaseStationSiliconLawCrescentStation
  abstract: true
  components:
  - type: SiliconLawProvider
    laws: NTDefault

- type: entity
  id: BaseStationSiliconLawCrescentShips
  abstract: true
  components:
  - type: SiliconLawProvider
    laws: Corporate

- type: entity
  id: BaseStationRenameFaxes
  abstract: true
  components:
    - type: StationRenameFaxes

# Sector-wide news access, should be on stations with comms (radio station, telecomms)
- type: entity
  id: BaseStationSectorNews
  abstract: true
  components:
    - type: SectorNews

- type: entity
  id: BaseCombatShipAlertLevels
  abstract: true
  components:
    - type: AlertLevel
      alertLevelPrototype: combatShipAlerts
